### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/connext-client#42]
- [x] only correct state updates lc
- [x] only correct parameters
- [x] verify all sigs
- [x] all requires met before contract calls
- [x] verify all LC decomposition
